services:
  tracking-number-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tracking-number-app-assignment
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_URI=${MONGODB_BASE_URI}&maxPoolSize=${MONGO_MAX_POOL_SIZE}&minPoolSize=${MONGO_MIN_POOL_SIZE}
