spring:
  application:
    name: trackingnumber-service

  data:
    mongodb:
      uri: "mongodb://localhost:27017/tracking-number-db-dev"
      auto-index-creation: true

  logging:
    level:
      root: "INFO"
      com.learning.trackingnumber_service: "DEBUG"

server:
  tomcat:
    threads:
      max: 20
      min-spare: 5
    max-connections: 500
    accept-count: 100

app:
  async:
    core-pool-size: 2
    max-pool-size: 10
    queue-capacity: 20





