spring:
  application:
    name: tracking-number-service # Your application's name
  data:
    mongodb:
      uri: mongodb://mongodb:${MONGODB_INNER_PORT}/tracking_number_dev_db
      auto-index-creation: false
      host: mongodb

server:
  port: ${SPRING_INNER_PORT} # The port on which your Spring Boot application will listen for incoming requests
  tomcat:
    threads:
      min-spare: 2
      max: 10
    accept-count: 100
    max-connections: 50

management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus

  metrics:
    export:
      cloudwatch:
        enabled: true
        namespace: TrackingNumberService

logging:
  level:
    root: INFO
    com.learning.trackingnumber_service: INFO


